CREATE OR REPLACE TRIGGER TR3_REGION 
BEFORE INSERT OR UPDATE OF REGION_NAME OR DELETE
ON REGIONES 
BEGIN
  IF USER <>'SYS' THEN
    RAISE_APPLICATION_ERROR(-20000,'SOLO HR PUEDE TRABAJAR EN REGIONS');
  END IF;
  
END;

UPDATE REGIONES SET REGION_NAME = 'XXXXX'
WHERE REGION_ID =1000;

SELECT *FROM REGIONES;